#!/usr/bin/env bash
# Writes the .env that the Aspire-generated docker-compose.yaml expects.
# Usage: deploy/write-env.sh <output-dir> <apiservice-image> <webfrontend-image>
set -euo pipefail

out_dir=$1
api_image=$2
web_image=$3

cat > "$out_dir/.env" <<ENV
# Generated by deploy/write-env.sh. Images are pinned by digest where available.
APISERVICE_IMAGE=$api_image
APISERVICE_PORT=8080
WEBFRONTEND_IMAGE=$web_image
WEBFRONTEND_PORT=8080
ENV
