<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <ContainerRepository>huttonhomehub/photomapper-migrations</ContainerRepository>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhotoMapper.Data\PhotoMapper.Data.csproj" />
    <ProjectReference Include="..\PhotoMapper.ServiceDefaults\PhotoMapper.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
